### ISSUE TITLE
Allow to change position and styles with CSS

### ISSUE THREAD

**Issue by al6x** [fgnass/spin.js#119]
For example - to correctly display spinner with Twitter Bootstrap sometimes its styles should be altered a little, it's already possible to do that with `important` and `.spinner > div > div` matchers, but would be nice to have explicit way to do that.

Would be nice to have explicit class `spinner-dot` for dots to set color via CSS and don't set styles via `style` attribute if for example `color: null` provided as an option.

``` CSS
.navigation .spinner > div > div {
  background-color: white !important;
}
.alert .spinner {
  display: inline-block;
  width: 8px !important;
  top: -6px !important;
}
```
