### ISSUE TITLE
Incorrect positioning when using column-count CSS property on parent

### ISSUE THREAD

**Issue by mflorence99** [fgnass/spin.js#252]
What a sweet piece of code! 

I'm showing a bunch of image thumbnails, organized into columns by applying a `column-count` CSS property to the parent. But when I apply the spinner, it only shows on the thumbnails in the leftmost column. I'm testing in Chrome 37. Could it be Google's problem in calculating the actual element position for DOM elements it has wrapped into another column?

```html
      <main class="thumbnails">
        <section class="thumbnail" ng-repeat="product in products"
            ng-click="showProduct(product, $event)">
          <img ng-src="{{ product.thumbnail }}">
        </section>
      </main>
```

```javascript
$scope.showProduct = function(product, $event) {
      var tgt = $event.currentTarget;
      var opts = { color: "#FFFFFF", shadow: true };
      new Spinner(opts).spin(tgt);
}
```

```less
/* just using less and lesshat mixins */
.thumbnails {
    .column-count(4);
    .column-gap(0);
    .column-width(auto);
    .thumbnail {
      position: relative;
    }
  }
```
